steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/isala.me:$SHORT_SHA"
      - "."
  - name: gcr.io/cloud-builders/docker
    args:
      - tag
      - "gcr.io/$PROJECT_ID/isala.me:$SHORT_SHA"
      - "gcr.io/$PROJECT_ID/isala.me:latest"
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "gcr.io/$PROJECT_ID/isala.me"
      - "--all-tags"
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - isala-me
      - "--image"
      - "gcr.io/$PROJECT_ID/isala.me:$SHORT_SHA"
      - "--region"
      - asia-southeast1
      - "--platform"
      - managed
      - "--timeout"
      - 10m
images:
  - "gcr.io/$PROJECT_ID/isala.me:$SHORT_SHA"
